name: e2e_ht
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.12
  - pip
  - pip:
      - absl-py==2.1.0
      - action-msgs==1.2.2
      - action-tutorials-interfaces==0.20.5
      - action-tutorials-py==0.20.5
      - actionlib-msgs==4.9.0
      - actuator-msgs==0.0.1
      - addict==2.4.0
      - ament-cmake-test==1.3.12
      - ament-copyright==0.12.14
      - ament-cppcheck==0.12.14
      - ament-cpplint==0.12.14
      - ament-flake8==0.12.14
      - ament-index-python==1.4.0
      - ament-lint==0.12.14
      - ament-lint-cmake==0.12.14
      - ament-package==0.14.1
      - ament-pep257==0.12.14
      - ament-uncrustify==0.12.14
      - ament-xmllint==0.12.14
      - angles==1.15.0
      - brotlipy==0.7.0
      - builtin-interfaces==1.2.2
      - cachetools==5.5.2
      - camera-calibration==3.0.8
      - certifi
      - cffi
      - charset-normalizer
      - click==8.1.8
      - composition-interfaces==1.2.2
      - cryptography
      - cv-bridge==3.2.1
      - cycler==0.11.0
      - demo-nodes-py==0.20.5
      - diagnostic-msgs==4.9.0
      - diagnostic-updater==4.0.6
      - dictor==0.1.12
      - diskcache==5.6.3
      - domain-coordinator==0.10.0
      - einops==0.6.1
      - ephem==4.2
      - example-interfaces==0.9.3
      - examples-rclpy-executors==0.15.4
      - examples-rclpy-minimal-action-client==0.15.4
      - examples-rclpy-minimal-action-server==0.15.4
      - examples-rclpy-minimal-client==0.15.4
      - examples-rclpy-minimal-publisher==0.15.4
      - examples-rclpy-minimal-service==0.15.4
      - examples-rclpy-minimal-subscriber==0.15.4
      - filelock==3.12.2
      - flit_core
      - fonttools==4.38.0
      - fsspec==2023.1.0
      - geometry-msgs==4.9.0
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - gps-msgs==2.1.1
      - grpcio==1.62.3
      - huggingface-hub==0.16.4
      - idna
      - image-geometry==3.2.1
      - imageio==2.31.2
      - importlib-metadata==6.7.0
      - interactive-markers==2.3.2
      - kiwisolver==1.4.5
      - laser-geometry==2.4.0
      - launch==1.0.10
      - launch-ros==0.19.10
      - launch-testing==1.0.10
      - launch-testing-ros==0.19.10
      - launch-xml==1.0.10
      - launch-yaml==1.0.10
      - lifecycle-msgs==1.2.2
      - logging-demo==0.20.5
      - map-msgs==2.1.0
      - Markdown==3.4.4
      - MarkupSafe==2.1.5
      - matplotlib==3.5.3
      - message-filters==4.3.8
      - mkl-fft==1.3.1
      - mkl-random
      - mkl-service==2.4.0
      - mmcv-full==1.5.3
      - mmdet==2.25.3
      - nav-msgs==4.9.0
      - networkx==2.6.3
      - numpy==1.21.6
      - oauthlib==3.2.2
      - opencv-python==4.12.0.88
      - osrf-pycommon==2.1.6
      - packaging==24.0
      - pandas==1.3.5
      - pcl-msgs==1.0.0
      - pendulum-msgs==0.20.5
      - Pillow==9.4.0
      - platformdirs==4.0.0
      - protobuf==3.20.3
      - py-trees==0.8.3
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.7
      - pycparser
      - pydot==2.0.0
      - pygame==2.1.2
      - pyOpenSSL
      - pyparsing==3.1.4
      - PySocks
      - python-dateutil==2.9.0.post0
      - python-qt-binding==1.1.2
      - pytz==2025.2
      - PyWavelets==1.3.0
      - PyYAML==6.0.1
      - qt-dotgraph==2.2.4
      - qt-gui==2.2.4
      - qt-gui-cpp==2.2.4
      - qt-gui-py-common==2.2.4
      - quality-of-service-demo-py==0.20.5
      - rcl-interfaces==1.2.2
      - rclpy==3.3.17
      - rcutils==5.1.6
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - resource-retriever==3.1.3
      - rmw-dds-common==1.6.0
      - ros-gz-interfaces==0.244.20
      - ros-ign-interfaces==0.244.20
      - ros2action==0.18.13
      - ros2bag==0.15.15
      - ros2cli==0.18.13
      - ros2component==0.18.13
      - ros2doctor==0.18.13
      - ros2interface==0.18.13
      - ros2launch==0.19.10
      - ros2lifecycle==0.18.13
      - ros2multicast==0.18.13
      - ros2node==0.18.13
      - ros2param==0.18.13
      - ros2pkg==0.18.13
      - ros2run==0.18.13
      - ros2service==0.18.13
      - ros2topic==0.18.13
      - rosbag2-interfaces==0.15.15
      - rosbag2-py==0.15.15
      - rosgraph-msgs==1.2.2
      - rosidl-adapter==3.1.7
      - rosidl-cli==3.1.7
      - rosidl-cmake==3.1.7
      - rosidl-generator-c==3.1.7
      - rosidl-generator-cpp==3.1.7
      - rosidl-generator-py==0.14.5
      - rosidl-parser==3.1.7
      - rosidl-runtime-py==0.9.3
      - rosidl-typesupport-c==2.0.2
      - rosidl-typesupport-cpp==2.0.2
      - rosidl-typesupport-fastrtps-c==2.2.2
      - rosidl-typesupport-fastrtps-cpp==2.2.2
      - rosidl-typesupport-introspection-c==3.1.7
      - rosidl-typesupport-introspection-cpp==3.1.7
      - rpyutils==0.2.1
      - rqt-action==2.0.1
      - rqt-bag==1.1.5
      - rqt-bag-plugins==1.1.5
      - rqt-console==2.0.3
      - rqt-graph==1.3.1
      - rqt-gui==1.1.7
      - rqt-gui-py==1.1.7
      - rqt-msg==1.2.0
      - rqt-plot==1.1.5
      - rqt-publisher==1.5.0
      - rqt-py-common==1.1.7
      - rqt-py-console==1.0.2
      - rqt-reconfigure==1.1.2
      - rqt-service-caller==1.0.5
      - rqt-shell==1.0.2
      - rqt-srv==1.0.3
      - rqt-topic==1.5.0
      - rsa==4.9.1
      - scikit-image==0.19.3
      - scipy==1.7.3
      - sensor-msgs==4.9.0
      - sensor-msgs-py==4.9.0
      - shape-msgs==4.9.0
      - shapely==2.0.7
      - six
      - sros2==0.10.7
      - statistics-msgs==1.2.2
      - std-msgs==4.9.0
      - std-srvs==4.9.0
      - stereo-msgs==4.9.0
      - svgwrite==1.4.3
      - tabulate==0.9.0
      - teleop-twist-keyboard==2.4.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - terminaltables==3.1.10
      - tf2-geometry-msgs==0.25.16
      - tf2-kdl==0.25.16
      - tf2-msgs==0.25.16
      - tf2-py==0.25.16
      - tf2-ros-py==0.25.16
      - tf2-sensor-msgs==0.25.16
      - tf2-tools==0.25.16
      - theora-image-transport==2.5.3
      - tifffile==2021.11.2
      - timm==0.6.13
      - tomli==2.0.1
      - topic-monitor==0.20.5
      - torch==1.11.0
      - torch-scatter==2.1.1
      - torchvision==0.12.0
      - tqdm==4.67.1
      - trajectory-msgs==4.9.0
      - Tree==0.2.4
      - turtlesim==1.4.2
      - typing_extensions==4.7.1
      - ujson==5.7.0
      - unique-identifier-msgs==2.2.1
      - urllib3==1.26.18
      - vision-msgs==4.1.1
      - visualization-msgs==4.9.0
      - Werkzeug==2.2.3
      - xacro==2.0.13
      - yacs==0.1.8
      - yapf==0.43.0
      - zipp==3.15.0
